name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:     
  DocumentatonJob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
           inputs: "COSC345-Lang"
           module-name: MyLibrary
           output: "Documentation"
           # # minimum-access-level: internal
      - name: Upload Documentation to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
           path: "Documentation"
        env:
           GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
           
  CoverageJob:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Coverage
        run: xcodebuild clean test -scheme COSC345-Lang -project COSC345-Lang/COSC345-Lang.xcodeproj -destination 'platform=iOS Simulator,OS=15.2,name=iPhone 11' -enableCodeCoverage YES 
      - name: Upload to CodeCov
        uses: codecov/codecov-action@v1.2.1

